name: build-docker-image
on:
  push:
    branches:
      - dev

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_DOCKER_PUSHER_AUTH }}

    # Setup auth gcloud
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.GCP_DOCKER_PUSHER_AUTH }}'

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate via gcloud command-line tool
        gcloud config set project summarize-text
        gcloud auth configure-docker europe-west1-docker.pkg.dev
      
    # Build the Docker image
    - name: Build
      run: |        
        docker build . --tag europe-west1-docker.pkg.dev/summarize-text-367819/docker-repository/first-flask-app

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push europe-west1-docker.pkg.dev/summarize-text-367819/docker-repository/first-flask-app
