name: 'Build Docker image'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    env:
          IMAGE_NAME: europe-west1-docker.pkg.dev/flask-cloud-368121/docker-repository/first-flask-app
    steps:
    - uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_DOCKER_PUSHER_AUTH }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'

    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Authenthification docker
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev
      
    # Build the Docker image
    - name: Build the Docker image
      run: |        
        docker build . --tag $IMAGE_NAME

    # Push the Docker image to Google Container Registry
    - name: Push to Google Container Registry
      run: |
        docker push $IMAGE_NAME